// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://ronyazdmazhsmhlwmxas.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvbnlhemRtYXpoc21obHdteGFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMwNDU4ODEsImV4cCI6MjA0ODYyMTg4MX0.KLCmbaZewUtVZpn4UvIPN9LtiQOZ_0hKSfQ9nCHW43o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);